
name: Тимур Лебедев 


description: Студент третьего курса СВФУ ИМИ


avatar: https://avatars1.githubusercontent.com/u/49018318?s=400&u=7dac87fbf868fdb1c7f12d526bd3066b7a5f5b4c&v=4


footer-links:
  email: viidzard@gmail.com
  vkontakte: https://vk.com/id282380537
  github: viidzard/viidzard.github.io
  instagram: https://www.instagram.com/yaoy_prince/
 






url: https://viidzard.github.io/

baseurl: ""



permalink: /:title/Блог Тимура Лебедева


version: v1.2.0


kramdown:

  input: GFM

  syntax_highlighter: rouge
  syntax_highlighter_opts:

    css_class: 'highlight'

sass:
  style: :expanded 

gems:
  - jekyll-sitemap 
  - jekyll-feed 


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
